### ISSUE TITLE
考虑微信支付的职位吗？

### ISSUE THREAD

**Issue by gaccob** [pflhm2005/Interview#1]
招全栈。  想做纯前端的话，也可以推荐兄弟部门。

![image](https://user-images.githubusercontent.com/4684354/81475515-58491180-923f-11ea-873e-addf40097e6b.png)

**Comment by pflhm2005** [comment]
啥东西，群发的吧，我可能要进微视了

**Comment by gaccob** [comment]
噢，已经在面试流程中了是吧？
那不打扰了。
